### PR TITLE
Use upstream IPA ramdisks instead of current-tripleo

### PR DESCRIPTION
**Pull request by dtantsur**
The TripleO project has been sunset, and the images have not been
updated since April. Use the images provided by Ironic.

### CODE REVIEW

**Comment by tuminoid** [comment]
You probably figured it out already as you've fixed the occurences, but you changed $FILENAME from static string to be dynamic (with possibility of having space), and hence it started complaining of all uses of $FFILENAME which contains $FILENAME, and hence also possibly contain spaces, and hence shellcheck started to complain.

**Comment by tuminoid** [comment]
Based on your question in Slack, me and @mboukhalfa checked what is actually happening in the integration test. It seems Ubuntu integration has a bug related to ipa-downloader and it does NOT use the image built from the PR to test IPA downloader, but pulls the image from Quay. Centos integration instead does use image built correctly.

See this test PR where Ubuntu incorrectly passes, but Centos fails as expected: https://github.com/metal3-io/ironic-ipa-downloader/pull/45

We will switch the required test thus to be centos-integration here: https://github.com/metal3-io/project-infra/pull/543
and will also work on the ubuntu-integration to fix the bug as well.

Meanwhile, you can run centos integration test to verify your change.

/test-centos-integration-main

**Comment by dtantsur** [comment]
Requires https://github.com/metal3-io/ironic-image/pull/423

**Review by iurygregory — COMMENTED** [review]
/lgtm

**Pull request merged**
