### PR TITLE
add tags as triggers for image builds

### PR DESCRIPTION
**Pull request by tuminoid**
We currently only build main branch,  and no tags. Add tag support.

### CODE REVIEW

**Comment by tuminoid** [comment]
/cc @dtantsur @elfosardo @zaneb @kashifest @Rozzii 

We want to build a release tag for this too (version matching Ironic-image), and need to add the tag as trigger. PTAL.

Related to #52

**Review by kashifest — COMMENTED** [review]
/approve

**Review by Rozzii — APPROVED** [review]
/lgtm

**Comment by kashifest** [comment]
Running prow CI to make it visible to branch protection
/test metal3-centos-e2e-integration-test-main

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-main 
This is not relevant, just unrelated test.

**Comment by tuminoid** [comment]
@elfosardo @dtantsur can we merge this, it is just enabler and doesn't do anything by itself.

**Comment by elfosardo** [comment]
@tuminoid yes, looks ok

**Comment by tuminoid** [comment]
> @tuminoid yes, looks ok

Can I then have an /approve or /lgtm too :wink:

**Comment by elfosardo** [comment]
/approve

sorry, I thought I added it!

**Review by Rozzii — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
Ping @dtantsur

**Pull request merged**
