### PR TITLE
Promote Iury to approvers, remove Stephen

### PR DESCRIPTION
**Pull request by dtantsur**
Iury is the Ironic PTL (project team lead) and has been consistently
reviewing ironic-image changes in his reviewer role.

Stephen has moved to another role.

### CODE REVIEW

**Comment by Rozzii** [comment]
Thanks @dtantsur !

**Comment by derekhiggins** [comment]
lgtm
holding back the / to all others to vote

**Review by elfosardo — APPROVED** [review]

**Pull request merged**
