### PR TITLE
Download from train branch

### PR DESCRIPTION
**Pull request by elfosardo**
Temporary moving back to master branch until train branch is
available.
This will allow to use the latest cool features.

### CODE REVIEW

**Comment by elfosardo** [comment]
let's hold on to this, the RDO stable/train branch should be available and we actually need that

**Comment by elfosardo** [comment]
@hardys @russellb @dhellmann @juliakreger @dtantsur @derekhiggins 
I don't have enough powers to assign the review, so just pinning people here
This change is necessary if we want to start using Train branch for Ironic and Ironic-inspector

**Comment by hardys** [comment]
Thanks @elfosardo I checked with tripleo/RDO folks and apparently the train images should be built "soon", ref https://review.rdoproject.org/r/#/c/22828/

However this does raise the question of how we want to consume Ironic in these upstream images, we might consider trunk-chasing here so that we can more pro-actively consume Ironic features as they are implemented?

I started a ml thread to discuss that idea, input welcome:  https://groups.google.com/forum/#!topic/metal3-dev/wdAVjp44kMY

I feel like that might work better for us where we have OpenShift forked repos that can be used for the stable ironic images, but I'm unclear exactly how the broader community would prefer to consume these images atm.

**Comment by elfosardo** [comment]
images from train are available so I'm going to change this to download from that branch
https://images.rdoproject.org/train/rdo_trunk/

**Comment by dtantsur** [comment]
/assign dtantsur

I'm not sure why it insists on bothering Julia..

**Comment by dtantsur** [comment]
/lgtm

what about now? :)

**Comment by dtantsur** [comment]
/approve

maybe now my voice has more power?

**Pull request merged**
